server:
  port: 7000
  servlet:
    context-path: /ad-sponsor    #Controller访问前缀

spring:
  application:
    name: eureka-client-ad-sponsor   #应用名称
  jpa:
    show-sql: true        #执行orm时，打印sql
    hibernate:
      ddl-auto: none     #加载hibernate时，根据配置直接生成或更新表结构，none时不更新
    properties:
      hibernate.format_sql: true  #格式化sql
    open-in-view: false

  datasource:
    url: jdbc:mysql://106.52.236.197:3306/ad?useUnicode=true&characterEncoding=utf-8&useSSL=false # 数据库地址、端口号、DB 需要根据你的配置去填 写
    username: root # 需要填写你的数据库用户名
    password: 123456 # 需要填写你的数据库密码
    tomcat:   # tomcat数据库连接池
      max-active: 4
      min-idle: 2
      initial-size: 2
eureka:
    client:
      service-url:
        defaultZone: http://localhost:8000/eureka/