server:
  port: 7002

spring:
  application:
    name: ad-dashboard   #应用名称

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/


management:
  endpoints:
    web:
      exposure:
        include: "*" #暴露全部监控信息